:-use_module(library(tty)).
:-include('questionario.pl').

% Predicado para o calculo dos niveis de transtorno
% Os acumuladores D0, D1, D2, D3, D4, D5 e D6 são para calculo do nível de transtorno de depressao
% Os acumuladores A0, A1, A2, A3, A4, A5 e A6 são para calculo do nível de transtorno de ansiedade
% Os acumuladores S0, S1, S2, S3, S4, S5 e S6 são para calculo do nível de transtorno de Estresse

questionario :-
	write_ln('-----------------------------------------------------------INICIO-----------------------------------------------------------'),
	questao_1(0,D0),
	write_ln(''),
	write_ln(''),
	questao_2(0,A0),
	write_ln(''),
	write_ln(''),
	questao_3(0,S0),
	write_ln(''),
	write_ln(''),
	questao_4(A0,A1),
	write_ln(''),
	write_ln(''),
	questao_5(D0,D1),
	write_ln(''),
	write_ln(''),
	questao_6(S0,S1),
	write_ln(''),
	write_ln(''),
	questao_7(A1,A2),
	write_ln(''),
	write_ln(''),
	questao_8(S1,S2),
	write_ln(''),
	write_ln(''),
	questao_9(A2,A3),
	write_ln(''),
	write_ln(''),
	questao_10(D1,D2),
	write_ln(''),
	write_ln(''),
	questao_11(S2,S3),
	write_ln(''),
	write_ln(''),
	questao_12(S3,S4),
	write_ln(''),
	write_ln(''),
	questao_13(D2,D3),
	write_ln(''),
	write_ln(''),
	questao_14(S4,S5),
	write_ln(''),
	write_ln(''),
	questao_15(A3,A4),
	write_ln(''),
	write_ln(''),
	questao_16(D3,D4),
	write_ln(''),
	write_ln(''),
	questao_17(D4,D5),
	write_ln(''),
	write_ln(''),
	questao_18(S5,S6),
	write_ln(''),
	write_ln(''),
	questao_19(A4,A5),
	write_ln(''),
	write_ln(''),
	questao_20(A5,A6),
	write_ln(''),
	write_ln(''),
	questao_21(D5,D6),
	write_ln(''),
	write_ln(''),
	X = D6,
	Y = A6,
	Z = S6,
	write_ln('------------------------------------------------------------RESULTADOS------------------------------------------------------------'),
	write_ln('Transtornos'),
	write_ln(''),
	write('Depressão: '),
	grau(doenca(depressao),X, Out_Depression),
	write_ln(''),
	write('Ansiedade: '),
	grau(doenca(ansiedade),Y, Out_Anxiety),
	write_ln(''),
	write('Estresse: '),
	grau(doenca(stress),Z, Out_Stress),
	write_ln('').

main :-
	write_ln('Segundo a OMS, “a saúde é um estado de completo bem-estar físico, mental e social e não apenas a ausência de doença ou enfermidade”. Mais especificamente, a saúde mental é um termo usado para descrever o nível de qualidade de vida cognitiva ou emocional. Dentro deste contexto, cada vez mais é necessário que conheçamos nossas forças e dificuldades, e para tal qualquer ação que aperfeiçoe o autoconhecimento pode auxiliar.'),
	write_ln('Tendo isso em mente, o objetivo do seguinte protótipo baseado no DASS-21 é calcular a escala de estresse, ansiedade e depressão, avaliando os resultados e mostrando a severidade dos sintomas dos disturbios mentais associados as doenças.'),
	write_ln('O DASS-21 usa um sistema de cálculo baseado em 21 perguntas, sendo 7 para cada doença, onde a pontuação máxima é 21 para cada doença.'),
	write_ln('Os níveis de doença são : Não há disturbio, Nivel médio de disturbio e Alto nível de Disturbio'),
	write_ln('É importante notar que esse sistema serve de apoio para melhor conhecer sua saúde mental, e não deve ser tomado como resultado final. Para mais informações busque ajuda médica'),
	write_ln('É importante notar que a resposta do usuario deve ser em um inteiro entre 0 a 3, e após cada resposta deve ser colocado o ponto final. A entrada de dados é sinalizada pela aparição dos símbolos |:.'),
	write_ln('As respostas são :'),
	write_ln('0 - Nunca'),
	write_ln('1 - Algumas vezes'),
	write_ln('2 - Mais da metade das vezes '),
	write_ln('3 - Quase sempre'),
	write_ln(''),
	write_ln(''),
	questionario.
